import { SidebarLink } from "@/types";

export const themes = [
  { value: "light", label: "Light", icon: "/assets/icons/sun.svg" },
  { value: "dark", label: "Dark", icon: "/assets/icons/moon.svg" },
  { value: "system", label: "System", icon: "/assets/icons/computer.svg" },
];
export const HomePageFilters = [
  { name: "Καινούργια", value: "newest" },
  { name: "Παλιά", value: "oldest" },
];

export const sidebarLinks: SidebarLink[] = [
  {
    imgURL: "/assets/icons/home.svg",
    route: "/",
    label: "Αρχική",
  },
  {
    imgURL: "/assets/icons/dashboard.svg",
    route: "/main",
    label: "Επισκόπηση",
  },

  {
    imgURL: "/assets/icons/form.svg",
    route: "/form",
    label: "Εισαγωγή Πελάτη",
  },
  {
    imgURL: "/assets/icons/clients.svg",
    route: "/clients",
    label: "Πελάτες",
  },
  {
    imgURL: "/assets/icons/calendar.svg",
    route: "/calendar",
    label: "Ημερολόγιο",
  },
  {
    imgURL: "/assets/icons/reservation.svg",
    route: "/createbooking",
    label: "Κρατήσεις",
  },

  {
    imgURL: "/assets/icons/chart.svg",
    route: "/logistics",
    label: "Ανάλυση",
  },

  {
    imgURL: "/assets/icons/expenses.svg",
    route: "/expenses",
    label: "Έξοδα",
  },
  {
    imgURL: "/assets/icons/question.svg",
    route: "/training",
    label: "Εκπαίδευση",
  },
];
export const mainCategoryColors = [
  "#FF6347",
  "#4682B4",
  "#32CD32",
  "#FFD700",
  "#9370DB",
  "#008080",
  "#8B4513",
  "#4169E1",
  "#FFA07A",
  "#556B2F",
  "#800080",
  "#20B2AA",
  "#FF69B4",
  "#000080",
];
export const Priority = [1, 2, 3];
export const TypesOfGender = ["Αρσενικό", "Θηλυκό"];
export const TypesOfFood = [
  "Ομοφαγία",
  "Μαγειρευτό",
  "Μπάρφ",
  "Ξηρά τροφή",
  "Υγρή τροφή",
  "Συνδυασμός",
];
export const TypesOfProfessions = [
  "Δάσκαλος/Δασκάλα",
  "Γιατρός",
  "Μηχανικός",
  "Δικηγόρος",
  "Λογιστής/Λογίστρια",
  "Αρχιτέκτονας/Αρχιτεκτόνισσα",
  "Προγραμματιστής",
  "Αγρότης/Αγρότισσα",
  "Πυροσβέστης",
  "Αστυνομικός",
  "Νοσηλευτής/Νοσηλεύτρια",
  "Φαρμακοποιός",
  "Οδηγός",
  "Σεφ",
  "Υπάλληλος",
  "Καλλιτέχνης",
  "Ηθοποιός",
  "Μουσικός",
  "Δημοσιογράφος",
  "Συγγραφέας",
  "Βιολόγος",
  "Χημικός",
  "Φυσικός",
  "Ψυχολόγος",
  "Κτηνίατρος",
  "Οδοντίατρος",
  "Πιλότος",
  "Ταμίας",
  "Κηπουρός",
  "Κομμωτής/Κομμώτρια",
  "Ηλεκτρολόγος",
  "Υδραυλικός",
  "Μάγειρας",
  "Ξυλουργός",
  "Πωλητής/Πωλήτρια",
  "Εργάτης/Εργάτρια",
  "Τεχνικός Υπολογιστών",
  "Μεταφραστής/Μεταφράστρια",
  "Αστρονόμος",
  "Γραφίστας",
  "Διευθυντής/Διευθύντρια",
  "Τραγουδιστής/Τραγουδίστρια",
  "Βιβλιοθηκονόμος",
  "Ταχυδρόμος",
  "Επιστήμονας",
];
export const TypesOfResidence = [
  "Μονοκατοικία",
  "Υπόγειο",
  "Ισόγειο",
  "1ος",
  "2ος",
  "3ος",
  "4ος",
  "5ος",
  "6ος",
  "7ος",
  "Εργασία",
];
export const TypesOfBehavior = [
  "Γαυγίζοντας",
  "Ανακουνώντας την ουρά",
  "Άλμα",
  "Κυνήγι",
  "Σκάψιμο",
  "Ενθουσιώδης",
  "Γλείψιμο",
  "Κοιμάται Συνέχεια",
  "Κύλισμα",
  "Προστασία",
  "Ποιμενικότητα",
  "Παιχνιδιάρικοτητα",
  "Επιθετικότητα",
  "Περιέργεια",
  "Παραπονιάρικο",
  "Κλάμα",
  "Κυνηγητικά ένστικτα",
  "Ανίχνευση οσμών",
  "Κοινωνικοποίηση",
  "Σήμανση του εδάφους",
  "Επιφυλακτικότητα",
  "Υποταγή",
  "Ενθουσιασμός",
  "Φόβος",
  "Φιλικότητα",
  "Νοημοσύνη",
  "Ανταπόκριση στην εκπαίδευση",
  "Ανεξαρτησία",
  "Στοργή",
  "Σφίγγει",
  "Εξερεύνηση",
  "Αντίδραση",
  "Προστασία των πόρων",
  "Αυτοπεποίθηση",
  "Συντροφικότητα",
  "Ευγενία",
  "Επίλυση προβλημάτων",
  "Ποιμενικά ένστικτα",
  "Πιστότητα",
  "Εδαφική συμπεριφορά",
  "Νευρικότητα",
  "Περιπολία",
  "Κυνηγητικό ένστικτο",
  "Ευκινησία",
  "Ηρεμία",
  "Κοινωνικότητα",
  "Αντικοινωνικότητα",
  "Κίνητρο για τροφή",
  "Παιχνίδι με το νερό",
  "Συμπεριφορά καλωσορίσματος",
  "Υποτακτικό",
  "Σπανιοπαθή",
  "Πονηρό",
  "Χτυπημός με το πόδι",
  "Σπρώξιμο",
  "Zoomies (ξαφνικές εκρήξεις ενέργειας)",
  "Ανεπιθύμητος",
];
export const TypesOfBreed = [
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Eskimo Dog",
  "American Staffordshire Terrier",
  "Anatolian Shepherd Dog",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Australian Terrier",
  "Barbet",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bedlington Terrier",
  "Belgian Malinois",
  "Belgian Sheepdog",
  "Belgian Tervuren",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black and Tan Coonhound",
  "Black Russian Terrier",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Brabancon Griffon",
  "Briard",
  "Brittany",
  "Brussels Griffon",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Canaan Dog",
  "Cane Corso",
  "Cardigan Welsh Corgi",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chinese Shar-Pei",
  "Chinook",
  "Chow Chow",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Coonhound",
  "Collie",
  "Curly-Coated Retriever",
  "Dachshund",
  "Dalmatian",
  "Dhole",
  "Dingo",
  "Doberman Pinscher",
  "Dogue de Bordeaux",
  "Dutch Shepherd",
  "English Bulldog",
  "English Cocker Spaniel",
  "English Foxhound",
  "English Setter",
  "English Springer Spaniel",
  "English Toy Spaniel",
  "Entlebucher Mountain Dog",
  "Eskimo Dog",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat-Coated Retriever",
  "French Bulldog",
  "German Pinscher",
  "German Shepherd",
  "German Shorthaired Pointer",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Goldador",
  "Golden Retriever",
  "Goldendoodle",
  "Gordon Setter",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Greyhound",
  "Harrier",
  "Havanese",
  "Hovawart",
  "Ibizan Hound",
  "Icelandic Sheepdog",
  "Irish Red and White Setter",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Japanese Spitz",
  "Japanese Terrier",
  "Jindo",
  "Kai Ken",
  "Karelian Bear Dog",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Klee Kai",
  "Korean Jindo Dog",
  "Kuvasz",
  "Labrador Retriever",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Leonberger",
  "Lhasa Apso",
  "Lowchen",
  "Maltese",
  "Manchester Terrier",
  "Maremma Sheepdog",
  "Mastiff",
  "Miniature Bull Terrier",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwegian Lundehund",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Peekapoo",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Petit Basset Griffon Vendeen",
  "Pharaoh Hound",
  "Plott",
  "Pointer",
  "Polish Lowland Sheepdog",
  "Pomeranian",
  "Poodle",
  "Portuguese Water Dog",
  "Pug",
  "Puggle",
  "Puli",
  "Pumi",
  "Pyrenean Mastiff",
  "Pyrenean Shepherd",
  "Rat Terrier",
  "Redbone Coonhound",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Silky Terrier",
  "Skye Terrier",
  "Sloughi",
  "Small Munsterlander Pointer",
  "Soft Coated Wheaten Terrier",
  "Spanish Water Dog",
  "Spinone Italiano",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Sussex Spaniel",
  "Swedish Vallhund",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Toy Fox Terrier",
  "Treeing Walker Coonhound",
  "Vizsla",
  "Weimaraner",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Wirehaired Pointing Griffon",
  "Xoloitzcuintli",
  "Yorkshire Terrier",
];

export const colors = [
  { label: "Tomato", value: "#FF6347" },
  { label: "SteelBlue", value: "#4682B4" },
  { label: "LimeGreen", value: "#32CD32" },
  { label: "Gold", value: "#FFD700" },
  { label: "MediumPurple", value: "#9370DB" },
  { label: "Teal", value: "#008080" },
  { label: "SaddleBrown", value: "#8B4513" },
  { label: "RoyalBlue", value: "#4169E1" },
  { label: "LightSalmon", value: "#FFA07A" },
  { label: "DarkOliveGreen", value: "#556B2F" },
  { label: "Purple", value: "#800080" },
  { label: "LightSeaGreen", value: "#20B2AA" },
  { label: "HotPink", value: "#FF69B4" },
  { label: "Navy", value: "#000080" },
];
