import { SidebarLink } from "@/types";

export const themes = [
  { value: "light", label: "Light", icon: "/assets/icons/sun.svg" },
  { value: "dark", label: "Dark", icon: "/assets/icons/moon.svg" },
  { value: "system", label: "System", icon: "/assets/icons/computer.svg" },
];

export const sidebarLinks: SidebarLink[] = [
  {
    imgURL: "/assets/icons/home.svg",
    route: "/",
    label: "Αρχική",
  },
  {
    imgURL: "/assets/icons/dashboard.svg",
    route: "/main",
    label: "Επισκόπηση",
  },
  {
    imgURL: "/assets/icons/form.svg",
    route: "/form",
    label: "Εισαγωγή Πελάτη",
  },
  {
    imgURL: "/assets/icons/transport.svg",
    route: "/createbooking",
    label: "Κρατήσεις",
  },
  {
    imgURL: "/assets/icons/bed.svg",
    route: "/rooms",
    label: "Δωμάτια",
  },
  {
    imgURL: "/assets/icons/chart.svg",
    route: "/logistics",
    label: "Ανάλυση",
  },
  {
    imgURL: "/assets/icons/calendar.svg",
    route: "/calendar",
    label: "Ημερολόγιο",
  },
  {
    imgURL: "/assets/icons/clients.svg",
    route: "/clients",
    label: "Πελάτες",
  },
  {
    imgURL: "/assets/icons/question.svg",
    route: "/training",
    label: "Εκπαίδευση",
  },
  {
    imgURL: "/assets/icons/transport.svg",
    route: "/transport",
    label: "Μεταφορά",
  },
];
export const Priority = [1, 2, 3];
export const TypesOfGender = ["Αρσενικό", "Θηλυκό", "Ζευγάρι"];
export const TypesOfFood = [
  "Acana",
  "Blue Buffalo",
  "Canidae",
  "Eukanuba",
  "Hill's Science Diet",
  "Iams",
  "Merrick",
  "Natural Balance",
  "Nutro",
  "Pedigree",
  "Purina Pro Plan",
  "Royal Canin",
  "Wellness",
  "Solid Gold",
  "Taste of the Wild",
  "Orijen",
  "Fromm",
  "Victor",
  "Artemis",
  "Diamond",
];
export const TypesOfResidence = ["Πολυκατοικία", "Μονοκατοικία"];
export const TypesOfBehavior = [
  "Γαυγίζοντας",
  "Ανακουνώντας την ουρά",
  "Άλμα",
  "Κυνήγι",
  "Σκάψιμο",
  "Ενθουσιώδης",
  "Γλείψιμο",
  "Κοιμάται Συνέχεια",
  "Κύλισμα",
  "Προστασία",
  "Ποιμενικότητα",
  "Παιχνιδιάρικοτητα",
  "Επιθετικότητα",
  "Περιέργεια",
  "Παραπονιάρικο",
  "Κλάμα",
  "Κυνηγητικά ένστικτα",
  "Ανίχνευση οσμών",
  "Κοινωνικοποίηση",
  "Σήμανση του εδάφους",
  "Επιφυλακτικότητα",
  "Υποταγή",
  "Ενθουσιασμός",
  "Φόβος",
  "Φιλικότητα",
  "Νοημοσύνη",
  "Ανταπόκριση στην εκπαίδευση",
  "Ανεξαρτησία",
  "Στοργή",
  "Σφίγγει",
  "Εξερεύνηση",
  "Αντίδραση",
  "Προστασία των πόρων",
  "Αυτοπεποίθηση",
  "Συντροφικότητα",
  "Ευγενία",
  "Επίλυση προβλημάτων",
  "Ποιμενικά ένστικτα",
  "Πιστότητα",
  "Εδαφική συμπεριφορά",
  "Νευρικότητα",
  "Περιπολία",
  "Κυνηγητικό ένστικτο",
  "Ευκινησία",
  "Ηρεμία",
  "Κοινωνικότητα",
  "Κίνητρο για τροφή",
  "Παιχνίδι με το νερό",
  "Συμπεριφορά καλωσορίσματος",
  "Υποτακτικό",
  "Σπανιοπαθή",
  "Πονηρό",
  "Χτυπημός με το πόδι",
  "Σπρώξιμο",
  "Zoomies (ξαφνικές εκρήξεις ενέργειας)",
];
export const TypesOfBreed = [
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Eskimo Dog",
  "American Staffordshire Terrier",
  "Anatolian Shepherd Dog",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Australian Terrier",
  "Barbet",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bedlington Terrier",
  "Belgian Malinois",
  "Belgian Sheepdog",
  "Belgian Tervuren",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black and Tan Coonhound",
  "Black Russian Terrier",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Brabancon Griffon",
  "Briard",
  "Brittany",
  "Brussels Griffon",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Canaan Dog",
  "Cane Corso",
  "Cardigan Welsh Corgi",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chinese Shar-Pei",
  "Chinook",
  "Chow Chow",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Coonhound",
  "Collie",
  "Curly-Coated Retriever",
  "Dachshund",
  "Dalmatian",
  "Dhole",
  "Dingo",
  "Doberman Pinscher",
  "Dogue de Bordeaux",
  "Dutch Shepherd",
  "English Bulldog",
  "English Cocker Spaniel",
  "English Foxhound",
  "English Setter",
  "English Springer Spaniel",
  "English Toy Spaniel",
  "Entlebucher Mountain Dog",
  "Eskimo Dog",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat-Coated Retriever",
  "French Bulldog",
  "German Pinscher",
  "German Shepherd",
  "German Shorthaired Pointer",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Goldador",
  "Golden Retriever",
  "Goldendoodle",
  "Gordon Setter",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Greyhound",
  "Harrier",
  "Havanese",
  "Hovawart",
  "Ibizan Hound",
  "Icelandic Sheepdog",
  "Irish Red and White Setter",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Japanese Spitz",
  "Japanese Terrier",
  "Jindo",
  "Kai Ken",
  "Karelian Bear Dog",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Klee Kai",
  "Korean Jindo Dog",
  "Kuvasz",
  "Labrador Retriever",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Leonberger",
  "Lhasa Apso",
  "Lowchen",
  "Maltese",
  "Manchester Terrier",
  "Maremma Sheepdog",
  "Mastiff",
  "Miniature Bull Terrier",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwegian Lundehund",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Peekapoo",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Petit Basset Griffon Vendeen",
  "Pharaoh Hound",
  "Plott",
  "Pointer",
  "Polish Lowland Sheepdog",
  "Pomeranian",
  "Poodle",
  "Portuguese Water Dog",
  "Pug",
  "Puggle",
  "Puli",
  "Pumi",
  "Pyrenean Mastiff",
  "Pyrenean Shepherd",
  "Rat Terrier",
  "Redbone Coonhound",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Silky Terrier",
  "Skye Terrier",
  "Sloughi",
  "Small Munsterlander Pointer",
  "Soft Coated Wheaten Terrier",
  "Spanish Water Dog",
  "Spinone Italiano",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Sussex Spaniel",
  "Swedish Vallhund",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Toy Fox Terrier",
  "Treeing Walker Coonhound",
  "Vizsla",
  "Weimaraner",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Wirehaired Pointing Griffon",
  "Xoloitzcuintli",
  "Yorkshire Terrier",
];
